---
# yaml-language-server: $schema=https://kubeschema.imranh.org/core/v1/persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  namespace: media
  labels:
    backup: daily
spec:
  storageClassName: zfs
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
# yaml-language-server: $schema=https://kubeschema.imranh.org/external-secrets.io/v1/externalsecret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome-lastfm-api
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  dataFrom:
    - extract:
        key: "Last.fm API"
  target:
    template:
      engineVersion: v2
      type: Opaque
      data:
        ND_LASTFM_APIKEY: "{{ .username }}"
        ND_LASTFM_SECRET: "{{ .credential }}"
---
# yaml-language-server: $schema=https://kubeschema.imranh.org/core/v1/configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-config
  namespace: media
data:
  navidrome.toml: |-
    TranscodingCacheSize = "4GB"
    Scanner.Enabled = true
    Scanner.Schedule = "12h"
    Tags.Genre.Split = ['; ']
    Agents = "audiomuseai,lastfm,spotify,deezer"
    AlbumPlayCountMode = "normalized"
---
# yaml-language-server: $schema=https://kubeschema.imranh.org/apps/v1/deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: media
  labels:
    app.kubernetes.io/name: navidrome
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: navidrome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: navidrome
    spec:
      containers:
        - name: navidrome
          image: ghcr.io/navidrome/navidrome:0.60.0
          ports:
            - containerPort: 4353
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          env:
            - name: ND_CONFIGFILE
              value: /etc/navidrome/navidrome.toml
            - name: ND_CACHEFOLDER
              value: /cache
          envFrom:
            - secretRef:
                name: navidrome-lastfm-api
          volumeMounts:
            - name: data
              mountPath: /data
            - name: media
              mountPath: /music
              subPath: Music
            - name: media
              mountPath: /new_music
              subPath: New Music
            - name: config
              mountPath: /etc/navidrome
            - name: cache
              mountPath: /cache
      volumes:
        - name: cache
          emptyDir:
            sizeLimit: 4Gi
        - name: config
          configMap:
            name: navidrome-config
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-data
        - name: media
          persistentVolumeClaim:
            claimName: media-store
---
# yaml-language-server: $schema=https://kubeschema.imranh.org/core/v1/service
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: media
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 4533
      port: 4533
      protocol: TCP
  selector:
    app.kubernetes.io/name: navidrome
