---
# yaml-language-server: $schema=https://kubeschema.imranh.org/core/v1/persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-store
  namespace: media
spec:
  storageClassName: zfs
  resources:
    requests:
      storage: 1.25Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
