---
# yaml-language-server: $schema=https://kubeschema.imranh.org/core/v1/persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: plex
spec:
  storageClassName: zfs
  resources:
    requests:
      storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
