---
# yaml-language-server: $schema=https://kubeschema.imranh.org/core/v1/configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: audiomuse-config
  namespace: audiomuse
data:
  TEMP_DIR: /app/temp_audio
  REDIS_URL: redis://redis:6379
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
