---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csi-external-snapshotter.yaml
  - external-secrets.yaml
  - velero.yaml
patches:
  # Specify default fetch interval & timeout
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
    patch: |-
      - op: replace
        path: /spec/interval
        value: 6h
      - op: add
        path: /spec/timeout
        value: 5m
