---
# yaml-language-server: $schema=https://kubeschema.imranh.org/source.toolkit.fluxcd.io/v1/gitrepository
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tailscale-crds
  namespace: flux-system
spec:
  interval: "1h" # This gets patched
  url: https://github.com/tailscale/tailscale.git
  ref:
    tag: "v1.86.5"
  # Exclude everything but the CRD directory
  ignore: |
    /*
    !/cmd/k8s-operator/deploy/crds
---
# yaml-language-server: $schema=https://kubeschema.imranh.org/kustomize.toolkit.fluxcd.io/v1/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-tailscale
  namespace: flux-system
spec:
  interval: "6h"
  sourceRef:
    kind: GitRepository
    name: tailscale-crds
  prune: false
  wait: true
