---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tailscale-crds
  namespace: flux-system
spec:
  interval: "1h" # This gets patched
  url: https://github.com/tailscale/tailscale.git
  ref:
    # TODO renovate
    tag: "v1.80.3"
  # Exclude everything but the CRD directory
  ignore: |
    /*
    !/cmd/k8s-operator/deploy/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-tailscale
  namespace: flux-system
spec:
  interval: "6h"
  sourceRef:
    kind: GitRepository
    name: tailscale-crds
  prune: false
  wait: true
