apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release-zfs-localpv.yaml
  - storageclass.yaml
  - snapshotclass.yaml
  - release-velero.yaml
  - backupstoragelocation.yaml
