---
# yaml-language-server: $schema=https://kubeschema.imranh.org/source.toolkit.fluxcd.io/v1/helmrepository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  url: https://jellyfin.github.io/jellyfin-helm
