---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets.yaml
  - metrics-server.yaml
  - zfs-localpv.yaml
  - vmware-tanzu.yaml
patches:
  # Specify default fetch interval & timeout
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: HelmRepository
    patch: |-
      - op: add
        path: /spec/interval
        value: 6h
      - op: add
        path: /spec/timeout
        value: 5m
