---
# yaml-language-server: $schema=https://kubeschema.imranh.org/source.toolkit.fluxcd.io/v1/helmrepository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
