---
# yaml-language-server: $schema=https://kubeschema.imranh.org/source.toolkit.fluxcd.io/v1/helmrepository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zfs-localpv
  namespace: flux-system
spec:
  url: https://openebs.github.io/zfs-localpv
