---
# yaml-language-server: $schema=https://kubeschema.imranh.org/cilium.io/v2alpha1/ciliumloadbalancerippool
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  blocks:
    - start: "192.168.1.75"
      stop: "192.168.1.99"
    - start: fd00::1:1
      stop: fd00::1:255
---
# yaml-language-server: $schema=https://kubeschema.imranh.org/cilium.io/v2alpha1/ciliuml2announcementpolicy
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
spec:
  nodeSelector:
    matchExpressions:
      # Control plane nodes should not be used for north-south traffic
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  loadBalancerIPs: true
  externalIPs: true
  interfaces:
    - ^enp[0-9]+s[0-9]+
