---
# yaml-language-server: $schema=https://kubeschema.imranh.org/cilium.io/v2alpha1/ciliumloadbalancerippool
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  blocks:
    - cidr: "192.168.2.0/24"
---
# yaml-language-server: $schema=https://kubeschema.imranh.org/cilium.io/v2alpha1/ciliuml2announcementpolicy
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
spec:
  nodeSelector:
    matchExpressions:
      # Control plane nodes should not be used for north-south traffic
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  loadBalancerIPs: true
