---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubelet-serving-cert-approver.yaml
  - metrics-server.yaml
  - openebs
patches:
  # Label namespaces
  - target:
      kind: Namespace
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: dontcare
        labels:
          layer: addons
