---
# yaml-language-server: $schema=https://kubeschema.imranh.org/kustomize.config.k8s.io/v1beta1/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-lb-ipam.yaml
  - kubelet-serving-cert-approver.yaml
  - metrics-server.yaml
  - storage
  - secrets
patches:
  # Label namespaces
  - target:
      kind: Namespace
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: dontcare
        labels:
          layer: addons
