# Credentials for this server are managed out-of-band.
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: secrets
spec:
  interval: 6h
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
      version: "~1.17.0"
  values:
    connect:
      # Server will not be used outside of this cluster
      serviceType: ClusterIP
