# yaml-language-server: $schema=https://kubeschema.imranh.org/kustomize.config.k8s.io/v1beta1/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secrets.yaml
  - secretstore.yaml
