---
# yaml-language-server: $schema=https://kubeschema.imranh.org/external-secrets.io/v1/clustersecretstore
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: Homelab
      auth:
        # Token is managed out-of-band.
        serviceAccountSecretRef:
          namespace: secrets
          name: onepassword-sa-token
          key: token
